version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"          # día específico
      time: "01:31"
      timezone: "America/Argentina/Buenos_Aires"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"       # label automático en los PRs
    ignore:
      - dependency-name: "*"
        update-types:        # ignorá major versions, son breaking changes
          - "version-update:semver-major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Argentina/Buenos_Aires"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Argentina/Buenos_Aires"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"